AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: el track service

Parameters:
  Environment:
    Type: String
    Description: specifies environment stage (local, dev, prod)
    Default: dev

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Handler: bootstrap
    Runtime: provided.al2023
    Architectures:
      - x86_64
    Environment:
        Variables:
          ENV: !Ref Environment

Resources:
  ElTrackLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/el-track-lambda
      Timeout: 5
      MemorySize: 128
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /el-track/{proxy+}
            Method: GET

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ElTrackAPI:
    Description: "API Gateway endpoint URL for el-track-lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ElTrackFunction:
    Description: "el-track-lambda function ARN"
    Value: !GetAtt ElTrackLambda.Arn
  ElTrackFunctionIamRole:
    Description: "Implicit IAM Role created for el-track-lambda function"
    Value: !GetAtt ElTrackLambda.Arn
